name: Reusable Test Workflow

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install common library locally
        working-directory: ismd-backend-validator-new
        run: ./mvnw -f ../ismd-validator-common/pom.xml -DskipTests install

      - name: Build with Maven
        working-directory: ismd-backend-validator-new
        run: ./mvnw clean package -DskipTests=true

      - name: Run tests
        working-directory: ismd-backend-validator-new
        run: ./mvnw test
